name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64
            manylinux: '2014'
            container: ghcr.io/pyo3/maturin:v1.13.3
            docker_options: --entrypoint /bin/bash
          - target: aarch64
            manylinux: '2014'
            container: ghcr.io/rust-cross/manylinux2014-cross:aarch64
            docker_options: ''
    steps:
    - uses: actions/checkout@v4
    - uses: PyO3/maturin-action@v1
      with:
        manylinux: ${{ matrix.manylinux }}
        container: ${{ matrix.container }}
        command: build
        target: ${{ matrix.target }}
        working-directory: xurdf-python
        docker-options: ${{ matrix.docker_options }}
        args: --release -o dist -i python3.10 -i python3.11
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.run_id }}-${{ github.job }}-${{ matrix.target }}
        path: xurdf-python/dist

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        working-directory: xurdf-python
        args: --release -o dist -i python3.10 -i python3.11
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.run_id }}-${{ github.job }}
        path: xurdf-python/dist

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        working-directory: xurdf-python
        args: --release -o dist -i python3.10 -i python3.11
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.run_id }}-${{ github.job }}
        path: xurdf-python/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ macos, windows, linux ]
    steps:
      - uses: actions/download-artifact@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*